language: java
sudo: required
jdk:
    - openjdk8
env:
    matrix:
        - ENGINE=lucee@5 COLDBOX_VERSION=stable
        - ENGINE=adobe@2018 COLDBOX_VERSION=stable
        - ENGINE=adobe@2016 COLDBOX_VERSION=stable
        - ENGINE=lucee@5 COLDBOX_VERSION=be
        - ENGINE=adobe@2018 COLDBOX_VERSION=be
        - ENGINE=adobe@2016 COLDBOX_VERSION=be
before_install:
    - curl -fsSl https://downloads.ortussolutions.com/debs/gpg | sudo apt-key add -
    - sudo echo "deb http://downloads.ortussolutions.com/debs/noarch /" | sudo tee -a /etc/apt/sources.list.d/commandbox.list
install:
    - sudo apt update && sudo apt --assume-yes install commandbox
    - box install commandbox-cfformat
    - box install
    - box install coldbox@${COLDBOX_VERSION} --force --!save
before_script:
    - box server start cfengine=$ENGINE port=8500
script:
    - box testbox run verbose=false
    - box run-script format:check
after_success:
    - box install commandbox-semantic-release
    - box config set endpoints.forgebox.APIToken=${FORGEBOX_TOKEN}
    - box semantic-release
notifications:
    email: false
